import type { TransportService } from "../transport.js";

type CapabilityRequestTransport = Pick<TransportService, "getConnections" | "sendCapabilityExecute">;

export function createMeshCapabilityRequestTool(transport: CapabilityRequestTransport, _ctx: any) {
  return {
    label: "Mesh Capability Request",
    name: "mesh_capability_request",
    description: "Ask a connected, approved mesh peer to run an advertised capability with an instruction.",
    parameters: {
      type: "object" as const,
      properties: {
        peerName: {
          type: "string",
          description: "Name of the connected, approved peer to ask.",
        },
        capability: {
          type: "string",
          description: "Capability tag to request, such as can:run-tests or has:xcode.",
        },
        instruction: {
          type: "string",
          description: "Instruction the remote peer should ask its local agent/user to handle.",
        },
        requestId: {
          type: "string",
          description: "Optional caller-provided request ID. If omitted, one is generated by the transport.",
        },
      },
      required: ["peerName", "capability", "instruction"] as string[],
    },
    execute: async (_toolCallId: string, toolParams: { peerName?: string; capability?: string; instruction?: string; requestId?: string }, _signal: any, _onUpdate: any) => {
      const peerName = toolParams?.peerName?.trim();
      const capability = toolParams?.capability?.trim();
      const instruction = toolParams?.instruction?.trim();
      const requestId = toolParams?.requestId?.trim();

      if (!peerName) {
        return {
          content: [{ type: "text" as const, text: "A peerName is required to request a mesh capability." }],
          details: { ok: false, error: "missing_peer_name" },
        };
      }
      if (!capability) {
        return {
          content: [{ type: "text" as const, text: "A capability is required to request remote execution." }],
          details: { ok: false, error: "missing_capability", peerName },
        };
      }
      if (!instruction) {
        return {
          content: [{ type: "text" as const, text: "An instruction is required to request remote capability execution." }],
          details: { ok: false, error: "missing_instruction", peerName, capability },
        };
      }

      const connections = transport.getConnections();
      if (!connections.includes(peerName)) {
        const connectedList = connections.length > 0 ? connections.join(", ") : "none";
        return {
          content: [{ type: "text" as const, text: `Peer '${peerName}' is not connected and approved. Connected approved peers: ${connectedList}.` }],
          details: { ok: false, error: "not_connected_or_approved", peerName, connectedPeers: connections },
        };
      }

      const sentRequestId = transport.sendCapabilityExecute(peerName, capability, instruction, requestId || undefined);
      if (!sentRequestId) {
        return {
          content: [{ type: "text" as const, text: `Could not send capability execution request to '${peerName}'. The peer may no longer be connected or approved.` }],
          details: { ok: false, error: "send_failed", peerName, capability, requestId },
        };
      }

      const providedRequestId = !!requestId;
      return {
        content: [{ type: "text" as const, text: `Sent capability execution request '${sentRequestId}' to '${peerName}' for '${capability}'. The peer will surface it for approval before running anything.` }],
        details: {
          ok: true,
          requestId: sentRequestId,
          providedRequestId,
          peerName,
          capability,
          instruction,
        },
      };
    },
  };
}
